name: cart-gui
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - numpy
  - matplotlib
  - scipy
  - pingouin
  - pyqt>=5.12
  - pip
  - pip:
    - PyQt5
    - matplotlib
    - pandas
    - numpy
    - scipy
    - pingouin>=0.3.12
